shell.run("pastebin get 2QpdPw5s Fuel")
shell.run("pastebin get KHNAXpTt Move")
shell.run("pastebin get UhmDMyGr Tree")
shell.run("pastebin get NFZMcNwe ReactorDisplay")
shell.run("pastebin get HN9T5uxA PeripherialCheck")
